
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pharmacy-db'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
